---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ahong.
--- DateTime: 2018/12/6 23:24
---
 function split(str,pattern)
    local tab = {}
    if(#pattern > 1) then
        str = string.gsub(str,pattern,",")
        pattern = ","
    end
    local begin = string.find(str,pattern)
    while begin
    do
        table.insert(tab,string.sub(str,1,begin-1))
        str = string.sub(str,begin+1)
        begin = str.find(str,pattern)
    end
    if not (str == "") then
        table.insert(tab,str)
    end
    return tab
end

local ss = "aabbccbbee"
local mytab = split(ss,"bb")
for k,v in pairs(mytab)
do
    print(k,v)
end