---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ahong.
--- DateTime: 2018/12/5 23:21
---
--local redis_cluster = require "resty.rediscluster"
--if(not redis_cluster) then
--    print("no")
--end
--print("yes")
print("good")
--error("fuck!")
print("bye")
print({})
print({})