---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ahong.
--- DateTime: 2018/12/9 8:54
---
local _M = {} -- 局部的变量
_M._VERSION = '1.0' -- 模块版本
local mt = { __index = _M }
function _M:new( width, height)
    return setmetatable({ width=width, height=height }, mt)
end
function _M:get_square()
    return self.width * self.height
end
function _M:get_circumference()
    return (self.width + self.height) * 2
end
return _M