---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ahong.
--- DateTime: 2018/12/9 8:55
---
local square = require "mylua.moduletest.square"
local s1 = square:new(1,2)
print(s1:get_circumference())
print(s1:get_square())